// <auto-generated />
using System;
using ContractManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250811203446_CheckDeleted")]
    partial class CheckDeleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ContractManager.Models.Dyspozycja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDyspozycji")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerUmowy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uzytkownik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dyspozycje");
                });
#pragma warning restore 612, 618
        }
    }
}
